/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package btllib;

public class BloomFilter {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BloomFilter(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BloomFilter obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        btllibJNI.delete_BloomFilter(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public BloomFilter() {
    this(btllibJNI.new_BloomFilter__SWIG_0(), true);
  }

  public BloomFilter(long bytes, long hash_num, String hash_fn) {
    this(btllibJNI.new_BloomFilter__SWIG_1(bytes, hash_num, hash_fn), true);
  }

  public BloomFilter(long bytes, long hash_num) {
    this(btllibJNI.new_BloomFilter__SWIG_2(bytes, hash_num), true);
  }

  public BloomFilter(String path) {
    this(btllibJNI.new_BloomFilter__SWIG_3(path), true);
  }

  public void insert(SWIGTYPE_p_unsigned_long_long hashes) {
    btllibJNI.BloomFilter_insert__SWIG_0(swigCPtr, this, SWIGTYPE_p_unsigned_long_long.getCPtr(hashes));
  }

  public void insert(SWIGTYPE_p_std__vectorT_unsigned_long_long_t hashes) {
    btllibJNI.BloomFilter_insert__SWIG_1(swigCPtr, this, SWIGTYPE_p_std__vectorT_unsigned_long_long_t.getCPtr(hashes));
  }

  public boolean contains(SWIGTYPE_p_unsigned_long_long hashes) {
    return btllibJNI.BloomFilter_contains__SWIG_0(swigCPtr, this, SWIGTYPE_p_unsigned_long_long.getCPtr(hashes));
  }

  public boolean contains(SWIGTYPE_p_std__vectorT_unsigned_long_long_t hashes) {
    return btllibJNI.BloomFilter_contains__SWIG_1(swigCPtr, this, SWIGTYPE_p_std__vectorT_unsigned_long_long_t.getCPtr(hashes));
  }

  public boolean contains_insert(SWIGTYPE_p_unsigned_long_long hashes) {
    return btllibJNI.BloomFilter_contains_insert__SWIG_0(swigCPtr, this, SWIGTYPE_p_unsigned_long_long.getCPtr(hashes));
  }

  public boolean contains_insert(SWIGTYPE_p_std__vectorT_unsigned_long_long_t hashes) {
    return btllibJNI.BloomFilter_contains_insert__SWIG_1(swigCPtr, this, SWIGTYPE_p_std__vectorT_unsigned_long_long_t.getCPtr(hashes));
  }

  public long get_bytes() {
    return btllibJNI.BloomFilter_get_bytes(swigCPtr, this);
  }

  public java.math.BigInteger get_pop_cnt() {
    return btllibJNI.BloomFilter_get_pop_cnt(swigCPtr, this);
  }

  public double get_occupancy() {
    return btllibJNI.BloomFilter_get_occupancy(swigCPtr, this);
  }

  public long get_hash_num() {
    return btllibJNI.BloomFilter_get_hash_num(swigCPtr, this);
  }

  public double get_fpr() {
    return btllibJNI.BloomFilter_get_fpr(swigCPtr, this);
  }

  public String get_hash_fn() {
    return btllibJNI.BloomFilter_get_hash_fn(swigCPtr, this);
  }

  public void save(String path) {
    btllibJNI.BloomFilter_save__SWIG_0(swigCPtr, this, path);
  }

  public static void save(String path, SWIGTYPE_p_cpptoml__table table, String data, long n) {
    btllibJNI.BloomFilter_save__SWIG_1(path, SWIGTYPE_p_cpptoml__table.getCPtr(table), data, n);
  }

}
