/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package btllib;

public class DataSource extends DataStream {
  private transient long swigCPtr;

  protected DataSource(long cPtr, boolean cMemoryOwn) {
    super(btllibJNI.DataSource_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DataSource obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        btllibJNI.delete_DataSource(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public DataSource(String path) {
    this(btllibJNI.new_DataSource(path), true);
  }

}
