/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package btllib;

public class Datatype {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Datatype(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Datatype obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        btllibJNI.delete_Datatype(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPrefixes(SWIGTYPE_p_std__vectorT_std__string_t value) {
    btllibJNI.Datatype_prefixes_set(swigCPtr, this, SWIGTYPE_p_std__vectorT_std__string_t.getCPtr(value));
  }

  public SWIGTYPE_p_std__vectorT_std__string_t getPrefixes() {
    long cPtr = btllibJNI.Datatype_prefixes_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__vectorT_std__string_t(cPtr, false);
  }

  public void setSuffixes(SWIGTYPE_p_std__vectorT_std__string_t value) {
    btllibJNI.Datatype_suffixes_set(swigCPtr, this, SWIGTYPE_p_std__vectorT_std__string_t.getCPtr(value));
  }

  public SWIGTYPE_p_std__vectorT_std__string_t getSuffixes() {
    long cPtr = btllibJNI.Datatype_suffixes_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__vectorT_std__string_t(cPtr, false);
  }

  public void setCmds_check_existence(SWIGTYPE_p_std__vectorT_std__string_t value) {
    btllibJNI.Datatype_cmds_check_existence_set(swigCPtr, this, SWIGTYPE_p_std__vectorT_std__string_t.getCPtr(value));
  }

  public SWIGTYPE_p_std__vectorT_std__string_t getCmds_check_existence() {
    long cPtr = btllibJNI.Datatype_cmds_check_existence_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__vectorT_std__string_t(cPtr, false);
  }

  public void setRead_cmds(SWIGTYPE_p_std__vectorT_std__string_t value) {
    btllibJNI.Datatype_read_cmds_set(swigCPtr, this, SWIGTYPE_p_std__vectorT_std__string_t.getCPtr(value));
  }

  public SWIGTYPE_p_std__vectorT_std__string_t getRead_cmds() {
    long cPtr = btllibJNI.Datatype_read_cmds_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__vectorT_std__string_t(cPtr, false);
  }

  public void setWrite_cmds(SWIGTYPE_p_std__vectorT_std__string_t value) {
    btllibJNI.Datatype_write_cmds_set(swigCPtr, this, SWIGTYPE_p_std__vectorT_std__string_t.getCPtr(value));
  }

  public SWIGTYPE_p_std__vectorT_std__string_t getWrite_cmds() {
    long cPtr = btllibJNI.Datatype_write_cmds_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__vectorT_std__string_t(cPtr, false);
  }

  public void setAppend_cmds(SWIGTYPE_p_std__vectorT_std__string_t value) {
    btllibJNI.Datatype_append_cmds_set(swigCPtr, this, SWIGTYPE_p_std__vectorT_std__string_t.getCPtr(value));
  }

  public SWIGTYPE_p_std__vectorT_std__string_t getAppend_cmds() {
    long cPtr = btllibJNI.Datatype_append_cmds_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__vectorT_std__string_t(cPtr, false);
  }

  public Datatype() {
    this(btllibJNI.new_Datatype(), true);
  }

}
