/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package btllib;

public class SeqReaderGfa2Module {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SeqReaderGfa2Module(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SeqReaderGfa2Module obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        btllibJNI.delete_SeqReaderGfa2Module(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SeqReaderGfa2Module() {
    this(btllibJNI.new_SeqReaderGfa2Module(), true);
  }

}
