.TH ABYSS "1" "2015-May" "ABYSS (ABySS) 1.9.0" "User Commands"
.SH NAME
ABYSS \- assemble short reads into contigs
.SH SYNOPSIS
.B ABYSS
[\fIOPTION\fR]... \fIFILE\fR...
.SH DESCRIPTION
Assemble all input files, FILE, which may be in FASTA, FASTQ, qseq,
export, SRA, SAM or BAM format and may be compressed with gz, bz2 or
xz and may be tarred.

Users wishing to run a full assembly with ABySS are recommended to
use abyss-pe as their entry point rather than the ABYSS program.
abyss-pe is a Makefile that coordinates many of the ABySS tools
(including ABYSS) in order to run the full ABySS assembly pipeline.
abyss-pe is capable of doing many things that ABYSS is not,
such as leveraging the distance information provided by paired end
reads and mate pair reads.
.TP
\fB--chastity\fR
discard unchaste reads [default]
.TP
\fB--no-chastity\fR
do not discard unchaste reads
.TP
\fB--trim-masked\fR
trim masked bases from the ends of reads [default]
.TP
\fB--no-trim-masked\fR
do not trim masked bases from the ends of reads
.TP
\fB-q\fR, \fB--trim-quality\fR=\fITHRESHOLD\fR
trim bases from the ends of reads whose quality is less than the
threshold
.TP
\fB-Q\fR, \fB--mask-quality\fR=\fITHRESHOLD\fR
mask all bases in reads whose quality is less than the threshold
.TP
\fB--standard-quality\fR
zero quality is `!' (33)
.br
default for FASTQ and SAM files
.TP
\fB--illumina-quality\fR
zero quality is `@' (64)
.br
default for qseq and export files
.TP
\fB\-o\fR, \fB\-\-out\fR=\fIFILE\fR
write the contigs to FILE
.TP
\fB\-k\fR, \fB\-\-kmer\fR=\fIKMER_SIZE\fR
k\-mer size
.TP
\fB\-t\fR, \fB\-\-trim\-length\fR=\fITRIM_LENGTH\fR
maximum length of dangling edges to trim
.TP
\fB\-c\fR, \fB\-\-coverage\fR=\fICOVERAGE\fR
remove contigs with mean k-mer coverage less than this threshold
.TP
\fB\-b\fR, \fB\-\-bubbles\fR=\fIN\fR
pop bubbles shorter than N bp (default: 3*k).
.TP
\fB\-b\fR0, \fB\-\-no\-bubbles\fR
do not pop bubbles
.TP
\fB\-e\fR, \fB\-\-erode\fR=\fICOVERAGE\fR
erode bases at the ends of blunt contigs with coverage less than this
threshold
.TP
\fB\-E\fR, \fB\-\-erode-strand\fR=\fICOVERAGE\fR
erode bases at the ends of blunt contigs with coverage less than this
threshold on either strand
.TP
\fB\-\-coverage-hist\fR=\fIFILE\fR
record the k-mer coverage histogram in FILE
.TP
\fB\-g\fR, \fB\-\-graph\fR=\fIFILE\fR
generate a graph in dot format
.TP
\fB\-s\fR, \fB\-\-snp\fR=\fIFILE\fR
record popped bubbles in FILE
.TP
\fB\-v\fR, \fB\-\-verbose\fR
display verbose output
.TP
\fB\-\-help\fR
display this help and exit
.TP
\fB\-\-version\fR
output version information and exit
.SH AUTHOR
Written by Jared Simpson and Shaun Jackman.
.SH "REPORTING BUGS"
Report bugs to <abyss-users@bcgsc.ca>.
.SH COPYRIGHT
Copyright 2015 Canada's Michael Smith Genome Sciences Centre
