.TH ABYSS "1" "2009-Aug" "ABYSS (ABySS) 1.0.13" "User Commands"
.SH NAME
ABYSS \- assemble short reads into contigs
.SH SYNOPSIS
.B ABYSS
[\fIOPTION\fR]... \fIFILE\fR...
.SH DESCRIPTION
Assemble all input files, FILE, which may be in FASTA (.fa) format or
FASTQ format (.fastq) and may be compressed with gz, bz2 or xz.
.TP
\fB--chastity\fR
discard unchaste reads [default]
for qseq- and export-formatted files only
.TP
\fB--no-chastity\fR
do not discard unchaste reads
.TP
\fB--trim-masked\fR
trim masked bases from the ends of reads [default]
.TP
\fB--no-trim-masked\fR
do not trim masked bases from the ends of reads
.TP
\fB\-o\fR, \fB\-\-out\fR=\fIFILE\fR
write the contigs to FILE
.TP
\fB\-k\fR, \fB\-\-kmer\fR=\fIKMER_SIZE\fR
k\-mer size
.TP
\fB\-l\fR, \fB\-\-read\-length\fR=\fIREAD_LENGTH\fR
read length
.TP
\fB\-t\fR, \fB\-\-trim\-length\fR=\fITRIM_LENGTH\fR
maximum length of dangling edges to trim
.TP
\fB\-c\fR, \fB\-\-coverage\fR=\fICOVERAGE\fR
remove contigs with mean k-mer coverage less than this threshold
[default=0]
.TP
\fB\-b\fR, \fB\-\-bubbles\fR=\fIN\fR
maximum number of bubble\-popping rounds
.TP
\fB\-\-erode\fR
erode bases at the ends of blunt contigs that are represented in only
one strand (enabled by default)
.TP
\fB\-e0\fR, \fB\-\-no-erode\fR
do not erode
.TP
\fB\-\-coverage-hist\fR=\fIFILE\fR
record the k-mer coverage histogram in FILE
.TP
\fB\-g\fR, \fB\-\-graph\fR=\fIFILE\fR
generate a graph in dot format
.TP
\fB\-s\fR, \fB\-\-snp\fR=\fIFILE\fR
record SNPs in FILE
.TP
\fB\-v\fR, \fB\-\-verbose\fR
display verbose output
.TP
\fB\-\-help\fR
display this help and exit
.TP
\fB\-\-version\fR
output version information and exit
.SH AUTHOR
Written by Jared Simpson and Shaun Jackman.
.SH "REPORTING BUGS"
Report bugs to <abyss-users@bcgsc.ca>.
.SH COPYRIGHT
Copyright 2009 Canada's Michael Smith Genome Science Centre
