.TH abyss-tofastq "1" "2011-Oct" "ABySS 1.3.1" "User Commands"
.SH NAME
abyss-tofastq \- convert various file formats to FASTQ format
.br
abyss-tofasta \- convert various file formats to FASTA format
.SH SYNOPSIS
\fBabyss-tofastq\fR [\fIFILE\fR]...
.br
or
.br
\fBabyss-tofasta\fR [\fIFILE\fR]...
.SH DESCRIPTION
Convert the input files to FASTA or FASTQ format. FILE may be in
FASTA, FASTQ, qseq, export, SRA, SAM or BAM format and may be
compressed with gz, bz2 or xz and may be tarred.
.SH AUTHOR
Written by Shaun Jackman.
.SH "REPORTING BUGS"
Report bugs to <abyss-users@bcgsc.ca>.
.SH COPYRIGHT
Copyright 2011 Canada's Michael Smith Genome Science Centre
