#!/bin/bash

if [ -z "${MESON_SOURCE_ROOT}" ]; then
  echo "[ERROR] This script can only be ran with meson!"
  exit 1
fi

cd "${MESON_SOURCE_ROOT}"

files=$(find tests -type f | grep "\(.*\.cpp$\)\|\(.*\.cxx$\)")
for file in $files; do
  echo -n "$(realpath $file) "
done